### ISSUE TITLE
Applying functional simplifications from proof hints.

### ISSUE THREAD

**Issue by nishantjr** [runtimeverification/proof-checker#462]
We use this definition as a running example:

```
syntax Tree ::= Int | node(Tree, Tree)
syntax Tree ::= reverse(Tree) [function, total]
rule [base-case]: reverse(I:Int) => I
rule [rec-case]:  reverse(node(T1, T2)) => node(reverse(T2), reverse(T1))

syntax KItem ::= "#Init"
syntax KItem ::= "#next"

rule [init]: <k> #init => #next </k>
rule [next]: <k> #next => reverse(node(1, 2)) </k>
```

There are three steps to extending a proof trace `init_config =>* curr_config`:

1.  First, given a rewrite rule `phi => psi` and the substitution theta to get
    `curr_config => next_config` where `curr_config = phi[theta]`,
    and `next_config = psi[theta]`.

2.  Second, we reduce unsimplified functions in `next_config` created as a result of applying the rule.
    For example `<foo> reverse(node(1, 2)) </foo>`
    must be reduced to `<foo> node(reverse(2), reverse(1)) </foo>`
    that is in turn reduced to `<foo> node(2, reverse(1)) </foo>`,
    and finally to `<foo> node(2, 1) </foo>`. (This Issue) 

3.  Third, we combine the proof of `init_config =>* curr_config` with `curr_config => next_config`
    to get `init_config =>* curr_config`. https://github.com/runtimeverification/proof-checker/issues/475

Let us go into detail about step 2.

Proof hints are specified by the following grammar (note the modification to function events):

````
    proof_trace ::= step_event* config events*
    step_event  ::= hook | function | rule
    event       ::= step_event | config
    hook        ::= WORD(0xAA) name argument* WORD(0xBB) kore_term
    function    ::= func_enter argument* func_exit
    func_enter  ::= WORD(0xDD) name location
    func_exit   ::= WORD(0x11)
    rule        ::= ordinal arity variable*
    config      ::= WORD(0xFF) tailed_term
    argument    ::= step_event | kore_term
````

The proof hint will look something like this:

```
rule_event: ordinal=next arity=0
function_enter_event: name=reverse location=(0:0)  (0th arg of <topCell>: 0th arg of <k> cell)
    rule_event: ordinal=rec-case arity=2 variables=[1; 2]
    function_enter_event: name=reverse location=(0)  (0th arg of node, in the result of the parent function call)
        rule_event: ordinal=rec-base arity=1 variables=[2]
    function_exit_event:
    function_enter_event: name=reverse location=(1)  (1st arg of node, in the result of the parent function call)
        rule_event: ordinal=rec-base arity=1 variables=[1]
    function_exit_event:
function_exit_event:
```

Let us annotate these with the proofs needed at each step:

```
rule_event: ordinal=next arity=0
// (1)   <k> #next </k> => <k> reverse(node(1, 2)) </k>
function_enter_event: name=reverse location=(0:0)  (0th arg of <topCell>: 0th arg of <k> cell)
    rule_event: ordinal=rec-case arity=2 variables=[1; 2]
    // NB: Since this is part of a function event, we use ==, instead of =>
    // simplification: (2) reverse(node(1, 2)) == node(reverse(2), reverse(1))
    function_enter_event: name=reverse location=(0)  (0th arg of node, in the result of the parent function call)
        rule_event: ordinal=rec-base arity=1 variables=[2]
        // (3) simplification: reverse(2) == 2
    function_exit_event:
    // Combining (2) and (3), and lifting (3) into the location (0), we get:
    // (4) lifting: reverse(node(1, 2)) == node(2, reverse(1))
    function_enter_event: name=reverse location=(1)  (1st arg of node, in the result of the parent function call)
        rule_event: ordinal=rec-base arity=1 variables=[1]
        // (5) simplification: reverse(2) == 1
    function_exit_event:
    // Combining (4) and (5), and lifting (5) into the location (1), we get:
    // lifting: (6) reverse(node(1, 2)) == node(2, 1)
function_exit_event:
// Combine (1) and (6), and lift (6) into the context (0:0) of the RHS of (2)
// lifting: (7)  <k> #next </k> => <k> node(2, 1) </k>```
```

Since the information we currently need from the proof-hints is incomplete (and as a good engineering practice in general),
we will split this task into two parts:

1. Extend the interface for ProofGenExp to allow functional simplifications tested using unit-tests, and
2. Drive that interface using the LLVM proof hints.

Task 2 is blocked on recieving the complete proof hints.

This issue will only deal with task 1.
At the moment, the proofs for rewrite (i.e. (1)) is more or less complete (waiting on #465 and #450).
We are left to deal with proofs for:

a. `simplification` (that is, (2), (3), and (5)).
b. `lifting` (that is (4), (6) and (7)

## Tasks

1.  #472

    Extend the interface for `LanguageSemantics` with the `equational_simplification` function
    that adds an `EquationalSimplification` instance.
    The list of axioms provided by the class. Add a unit test for this

2.  #532 

3. #516 

4. #548  [Depends on 3., 1.]

5. #473  

6. #513

7. #514 [Depends on 5, 6, 4]

8. #645 

9. #646 

10. #647 

11. #648

12. #459
